<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "moox_feusers"
 *
 * Auto generated by Extension Builder 2014-02-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MOOX feusers',
	'description' => 'Manage feusers, login, register, edit, create, delete',
	'category' => 'plugin',
	'author' => 'Dominic Martin',
	'author_email' => 'dm@dcn.de',
	'author_company' => 'DCN GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.8.2',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',			
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>