<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "moox_feusers"
 *
 * Auto generated by Extension Builder 2014-02-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MOOX feusers',
	'description' => 'Manage feusers in a comfortable Backend-Module including Editor for system-mails.',
	'category' => 'plugin',
	'author' => 'MOOX Team',
	'author_email' => 'moox@dcn.de',
	'author_company' => 'DCN GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.8.5',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'moox_core' => '0.9.8-1.9.99'			
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
